"""Turn raw generated bytes into the desired final file on disk.

`stretch` ignores aspect ratio (plain resize). Every anchor mode is a cover-crop
handled by one `ImageOps.fit` call whose `centering` tuple picks the anchor.
"""

from __future__ import annotations

import io
from pathlib import Path

from PIL import Image, ImageOps

from ai_image_creator.models import CropMode, OutputSpec

# Anchor -> ImageOps.fit centering (x, y), each in 0.0..1.0.
_CENTERING: dict[CropMode, tuple[float, float]] = {
    CropMode.CENTER: (0.5, 0.5),
    CropMode.TOP: (0.5, 0.0),
    CropMode.BOTTOM: (0.5, 1.0),
    CropMode.LEFT: (0.0, 0.5),
    CropMode.RIGHT: (1.0, 0.5),
}


def resize_and_crop(data: bytes, spec: OutputSpec) -> bytes:
    """Return final image bytes for `spec`. No resize -> re-encode as-is to format."""
    with Image.open(io.BytesIO(data)) as opened:
        mode = "RGBA" if spec.format.lower() == "png" else "RGB"
        img: Image.Image = opened.convert(mode)

        if spec.has_resize:
            assert spec.width is not None and spec.height is not None
            target = (spec.width, spec.height)
            if spec.crop is CropMode.STRETCH:
                img = img.resize(target)
            else:
                img = ImageOps.fit(img, target, centering=_CENTERING[spec.crop])

        out = io.BytesIO()
        img.save(out, format=_pillow_format(spec.format))
        return out.getvalue()


def save(data: bytes, path: str) -> Path:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_bytes(data)
    return target


def _pillow_format(fmt: str) -> str:
    normalized = fmt.lower()
    return "JPEG" if normalized in ("jpg", "jpeg") else normalized.upper()
